# Generated by Django 4.1.1 on 2022-10-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='subject',
        ),
    ]
