# Generated by Django 4.1.1 on 2022-12-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0003_articles_photo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='subject',
            field=models.CharField(default='no_subject', max_length=100),
        ),
    ]
