# Generated by Django 4.1.1 on 2023-01-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0004_articles_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
