# Generated by Django 4.1.1 on 2023-01-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0005_articles_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='cart',
            field=models.BooleanField(default=False),
        ),
    ]
